export enum HttpStatusCode {
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER = 500,
  SUCCESS = 200,
}

export enum HttpStatusCodeName {
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD REQUEST',
  NOT_AUTHORIZED = 'NOT AUTHORIZED',
  INTERNAL_SERVER = 'INTERNAL SERVER',
}
